version: '3.9'

services:
  database:
    image: mysql:8.0.34
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_management
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
    ports:
      - "5672:5672" # RabbitMQ service port
      - "15672:15672" # RabbitMQ management console
    networks:
      - app_network

volumes:
  db_data:

